version: '3.8'

services:
  viruela_mono-api:
    image: rogercc28/viruela_mono-api:latest
    container_name: viruela_mono_api
    ports:
      - "3000:3000"
    environment: 
      MONGO_URL: mongodb://root:example@mongo/
      PORT: 3000
      MAIL_SECRET_KEY: zasoudkvnrzdwulm 
      MAIL_SERVICE: gmail
      MAIL_USER: rogelioceballos218@gmail.com
      MAPBOX_ACCESS_TOKEN: pk.eyJ1IjoianVhbmZyOTciLCJhIjoiY2x4cnhqZGZpMWUzdTJrb2Qxd2k5Z3huYSJ9.Kp99lB1snn3xzzi26jKy4w
    depends_on:
      - mongo


  mongo: 
    image: mongo
    container_name: mongo_monkey_pox
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: